### PR TITLE
Fixes descriptions in the Inference APIs

### LINKED ISSUE #5508: Missing prerequisites in the Inference API documentation
https://www.elastic.co/docs/api/doc/elasticsearch/v9/operation/operation-inference-get
The endpoint is missing the following prerequisites: “Requires the monitor_inference cluster privilege (the built-in inference_admin and inference_user roles grant this privilege)”

https://www.elastic.co/docs/api/doc/elasticsearch/v9/operation/operation-inference-delete
The endpoint in the new docs misses the following prerequisite description: Requires the manage_inference cluster privilege (the built-in inference_admin role grants this privilege)

### PR DESCRIPTION
**Pull request by kosabogi**
This PR fixes description errors discovered during the https://github.com/elastic/docs-content-internal/issues/280 of the 8.x and 9.x API documentation.

Closes #5508, #5509, #5510, #5511, #5512

### CODE REVIEW

**Review by leemthompo — DISMISSED** [review]

File: specification/inference/delete/DeleteRequest.ts [hunk 1]
```diff
@@ -23,6 +23,7 @@ import { TaskType } from '@inference/_types/TaskType'
 
 /**
  * Delete an inference endpoint
+ * This API requires the manage_inference cluster privilege (the built-in inference_admin role grants this privilege).
```
Comment (leemthompo) [inline specification/inference/delete/DeleteRequest.ts]:
```suggestion
 * This API requires the manage_inference cluster privilege (the built-in `inference_admin` role grants this privilege).
```

File: specification/inference/put_cohere/PutCohereRequest.ts [hunk 2]
```diff
@@ -65,6 +65,8 @@ export interface Request extends RequestBase {
   body: {
     /**
      * The chunking configuration object.
+     * Applies only to the `sparse_embedding` and `text_embedding` task types.
+     * Not applicable to the `rerank`, `completion`, or `chat_completion` task types.
```
Comment (leemthompo) [inline specification/inference/put_cohere/PutCohereRequest.ts]: These generic messages might be confusing, because for example Cohere only supports the following task types:

- completion
- rerank
- text_embedding

So consider deleting `sparse_embedding` and `chat_completion` here. I'd inspect all of these services to avoid confusing users by mention applicabilities that aren't available

Comment (kosabogi) [reply specification/inference/put_cohere/PutCohereRequest.ts]: You’re absolutely right. Thinking it through, that also means `chunking_settings` isn’t applicable for certain inference endpoints, even though now it appears for all of them. Could this be a bug, @davidkyle?
For example, the [Create an Anthropic inference endpoint API](https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-inference-put-anthropic) supports only one task type  (completion) so chunking doesn’t apply there.

File: specification/inference/_types/CommonTypes.ts [hunk 3]
```diff
@@ -391,7 +391,7 @@ export class AlibabaCloudTaskSettings {
 export enum AlibabaCloudTaskType {
   completion,
   rerank,
-  space_embedding,
+  sparse_embedding,
```
Comment (davidkyle) [inline specification/inference/_types/CommonTypes.ts:394]: 😁

File: specification/inference/put/PutRequest.ts [hunk 4]
```diff
@@ -51,6 +51,13 @@ import { TaskType } from '@inference/_types/TaskType'
  * * OpenAI (`chat_completion`, `completion`, `text_embedding`)
  * * VoyageAI (`rerank`, `text_embedding`)
  * * Watsonx inference integration (`text_embedding`)
+ *
+ * NOTE: When creating an inference endpoint, the associated machine learning model is automatically deployed if it is not
+ * already running. After creating the endpoint, wait for the model deployment to complete before using it. You can verify
+ * the deployment status by using the Get trained model statistics API. In the response, look for "state": "fully_allocated"
+ * and ensure the "allocation_count" matches the "target_allocation_count". Avoid creating multiple endpoints for the same
+ * model unless required, as each endpoint consumes significant resources.
+ *
```
Comment (davidkyle) [inline specification/inference/put/PutRequest.ts]: This text is in `PutElasticsearchRequest.ts` and `PutElserRequest.ts` and specific to those inference services we don't need it here too

```suggestion
```

File: specification/inference/put_cohere/PutCohereRequest.ts (hunk 2 above)
Comment (davidkyle) [reply specification/inference/put_cohere/PutCohereRequest.ts]: Yes chunking_settings only applies to the text_embedding and sparse_embedding task types

File: specification/inference/_types/CommonTypes.ts (hunk 3 above)
Comment (leemthompo) [reply specification/inference/_types/CommonTypes.ts:394]: 🧑‍🚀
