### PR TITLE
Fix misc issues found with java-client+recordings

### LINKED ISSUE #1887: Java-client+recordings validation errors - Misc
These errors were found when loading recordings in the Java client. Do not forget to **backport relevant changes to 7.17**, which is still maintained.

Field names reported can be either in their json form (`snake_case`) or in their Java form (`camelCase`) depending on the context. If the messages sound cryptic, ask @swallez for an explanation!

Errors coming from Nest tests should be taken with a grain of salt, since these recordings are quite old now and were captured with ES 7.x

```
enrich.get_policy response: Error deserializing co.elastic.clients.elasticsearch.enrich.EnrichSummary: co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'EnrichConfiguration.range' (JSON path: policies[0].config)  (×6)
    elasticsearch/tmp-platinum/enrich.get_policy/b9a03549c0d0dc87c3645764b9cf1661.json
    elasticsearch/tmp-platinum/enrich.get_policy/027f835799c528ccde6e347855828bac.json
    nest-tests/enrich.get_policy/XPack/Enrich/EnrichApiTests/EnrichApiTests__.ctor_b__5_24_2750__response.json
    nest-tests/enrich.get_policy/XPack/Enrich/EnrichApiTests/EnrichApiTests__.ctor_b__5_23_2749__response.json
    nest-tests/enrich.get_policy/XPack/Enrich/EnrichApiTests/EnrichApiTests__.ctor_b__5_22_2748__response.json
    nest-tests/enrich.get_policy/XPack/Enrich/EnrichApiTests/EnrichApiTests__.ctor_b__5_21_2747__response.json

ingest.simulate response: Error deserializing co.elastic.clients.elasticsearch.ingest.simulate.DocumentSimulation: Unknown field '_version' (JSON path: docs[0].doc._version)  (×2)
    elasticsearch/tmp-platinum/ingest.simulate/5bd9d9a20f65040acf2f555cdf5cd213.json
    elasticsearch/tmp-platinum/ingest.simulate/b14ddca74bc0da694bf56e39b8f2d231.json

license.post request: Missing required property 'PostRequest.licenses' (×1)
    elasticsearch/tmp-platinum/license.post/8aac42b9730675bf981a0b2304445c82.json

ssl.certificates response: Error deserializing co.elastic.clients.elasticsearch.ssl.certificates.CertificateInformation: Unknown field 'issuer' (JSON path: [0].issuer)  (×1)
    elasticsearch/tmp-platinum/ssl.certificates/084ca1601f4050d21afbc9c229e6fbc6.json

ssl.certificates response: Error deserializing: co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'CertificateInformation.alias' (JSON path: [0])  (×1)
    nest-tests/ssl.certificates/XPack/Ssl/GetCertificates/GetCertificatesApiTests/GetCertificatesApiTests__ClientUsage_b__11_2_2204__response.json

transform.preview_transform request: Error deserializing co.elastic.clients.elasticsearch.transform.Settings: Unknown field 'unattended' (JSON path: settings.unattended)  (×1)
    elasticsearch/tmp-platinum/transform.preview_transform/4573dfa21d191fcba6cb40a09cd1558f.json

transform.put_transform request: Error deserializing co.elastic.clients.elasticsearch.transform.Settings: Unknown field 'unattended' (JSON path: settings.unattended)  (×2)
    elasticsearch/tmp-platinum/transform.put_transform/97a7d0cc4bee5b58708b1bc0f427da64.json
    elasticsearch/tmp-platinum/transform.put_transform/e6d94ea75203e5f490c627cf777c3aa2.json

xpack.usage response: Error deserializing co.elastic.clients.elasticsearch.xpack.usage.MlInferenceTrainedModelsCount: Unknown field 'pass_through' (JSON path: ml.inference.trained_models.count.pass_through)  (×6)
    elasticsearch/tmp-platinum/xpack.usage/cdf95ba4f92cd623b6537abad8dac03d.json
    elasticsearch/tmp-platinum/xpack.usage/b8d0a725de42d7ab987e96fe989184d1.json
    elasticsearch/tmp-platinum/xpack.usage/7c7dea0dfee5049ed421eb5ba97da3a2.json
    elasticsearch/tmp-platinum/xpack.usage/7a8f6d6a93037b10f322b20162295744.json
    elasticsearch/tmp-platinum/xpack.usage/f519d3ad71416cb1a5f266e694505b54.json
    elasticsearch/tmp-platinum/xpack.usage/d84a2e59e7c452aa5ed7f8da57a1dc49.json

```

### PR DESCRIPTION
**Pull request by swallez**
Fixes #1887

### CODE REVIEW

File: specification/ml/_types/Job.ts [hunk 1]
```diff
@@ -49,28 +50,33 @@ export class JobStatistics {
 }
 
 export class Job {
```
Comment (sethmlarson) [inline specification/ml/_types/Job.ts:52]: This change is making everything optional, should wherever this type is used instead use `JobConfig`?

File: specification/ingest/simulate/types.ts [hunk 2]
```diff
@@ -42,11 +43,12 @@ export class Document {
...
 }
 
-export class DocumentSimulation {
-  _id: Id
-  _index: IndexName
+/**
+ * The simulated document, with optional metadata.
+ */
+export class DocumentSimulation
+  implements AdditionalProperties<string, string>
```
Comment (sethmlarson) [inline specification/ingest/simulate/types.ts:50]: I'm curious about this change, aren't the `_id`, `_index`, etc fields well-defined for this object?

**Review by sethmlarson — COMMENTED** [review]
Looks great, few thoughts:

File: specification/ingest/simulate/types.ts (hunk 2 above)
Comment (swallez) [reply specification/ingest/simulate/types.ts:50]: I looked at the ES source code and the only fields that are defined there are `_ingest` and `_source`. Everything else is a string->string metadata dictionary. So there's actually no guarantee that `_id` and `_index` will always be there, even if they happen to always be present in our recordings.

What triggered me to look at the code is that there was a missing `_version` field that is a number in a string. So I wanted to understand why it wasn't a real number and discovered this metadata dictionary 😉

File: specification/ml/_types/Job.ts (hunk 1 above)
Comment (swallez) [reply specification/ml/_types/Job.ts:52]: Hmm... it could indeed extend `JobConfig` (with the only difference being that `analysis_config` is required in `JobConfig`). Is this what you mean?

I ended up making all fields optional after a number of validation iterations where they were all successively reported as "missing required field"

File: specification/ingest/simulate/types.ts (hunk 2 above)
Comment (sethmlarson) [reply specification/ingest/simulate/types.ts:50]: Interesting! The implementation shouldn't dictate the API contract though IMO. If certain fields like `_id` and `_index` are always there I think it makes sense to continue having at least those two fields in our API spec?

File: specification/ml/_types/Job.ts (hunk 1 above)
Comment (sethmlarson) [reply specification/ml/_types/Job.ts:52]: I'm wondering if this issue you're running into is the same as what I was trying to fix in https://github.com/elastic/elasticsearch-specification/pull/1283 but couldn't complete due to needing to use an `OverloadOf` class as a type of one of the subproperties IIRC?

For now can we maintain two classes `Job` and `JobRead` where `JobRead` has all properties as they are today and another class `Job` with the definition you have in this PR? What are your thoughts on this approach?
